# Generated by Django 5.1.7 on 2025-04-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='ano',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
